sudo: false
language: ruby
rvm:
  - 2.1
  - 2.4
  - 2.5
  - 2.6
  - jruby-9.1.9.0
before_install:
  - gem update --system --conservative || (gem i "rubygems-update:~>2.7" --no-document && update_rubygems)
  - gem update bundler --conservative
